project:
  type: website
  resources: "static/img/tmview-1.html"

website:
  favicon: "static/favicon.ico"
  # twitter-card: true
  # open-graph: true
  title: "geocompx"
  site-url: https://geocompx.org/
  description: "geocompx hosts free resources on reproducible geographic data analysis, modelling and visualization with open source software"
  navbar:
    # logo: "static/geocompx-text.png"
    logo: "static/geocompx-logo-h.png"
    logo-alt: "geocompx"
    title: false
    left:
      - href: post.qmd
        text: Posts
      - href: r.qmd
        text: R resources
      - href: py.qmd
        text: Python resources
      - href: jl.qmd
        text: Julia resources
      - href: guestbook.qmd
        text: Guestbook
      - href: about.qmd
        text: About us
    right:
      - href: https://donate.stripe.com/4gweWl94Q9E35AQ6oo
        text: Support this project
      - icon: twitter
        href: https://twitter.com/hashtag/geocompx
      - icon: mastodon
        href: https://fosstodon.org/tags/geocompx
      - icon: discord
        href: https://discord.gg/PMztXYgNxp
      - icon: rss
        href: post.xml
  google-analytics: "G-PS0D9S7P17"
  page-footer: 
     left: "geocompx, 2016 - 2024" 
     right:
      - icon: github
        href: https://github.com/geocompx/geocompx.org

format:
  html:
    theme: 
      - simplex
      - styles.scss
    css: style.css
    toc: true

execute: 
  freeze: auto