---
title-prefix: "geocompx"
title: "Guestbook"
page-layout: full
---

##### ([suggest more here](https://github.com/geocompx/geocompx.org/edit/main/guestbook.qmd))

[Elegant and informative maps with tmap](https://r-tmap.github.io/tmap-book/) from Martijn Tennekes, Jakub Nowosad

[Spatial Data Science with applications in R](https://r-spatial.org/book/) from Edzer Pebesma, Roger Bivand with [solutions](https://edzer.github.io/sdsr_exercises/)


## Geocomputation with R

### Modules using the book

- [CASA0005 Geographic Information Systems and Science](https://andrewmaclachlan.github.io/CASA0005repo/), [Andy MacLachlan](https://twitter.com/andymaclachlan) and [Adam Dennett](https://twitter.com/adam_dennett), Centre for Advanced Spatial Analysis, Univeristy College London
- [ECS530 Analysing spatial data](https://www.nhh.no/en/courses/analysing-spatial-data/), [Roger Bivand](https://www.nhh.no/en/employees/faculty/roger-bivand/), Norwegian School of Economics
- [GEOG 495](http://geog.uoregon.edu/bartlein/courses/geog495/readings.html) and [595: Geographic Data Analysis](https://pjbartlein.github.io/GeogDataAnalysis/), University of Oregon
- [ESPM 288: Reproducible and Collaborative Data Science](https://espm-288.carlboettiger.info/), [Berkeley](https://classes.berkeley.edu/content/2018-spring-espm-288-001-lab-001) University of California
<!-- [Stat 6864 Introduction to Data Science](http://www.sci.csueastbay.edu/~esuess/stat6864/) -->
- [ENVR_SCI 390-0 "R Data Science" - Special Topics in Environmental Sciences](https://www.northwestern.edu/class-descriptions/4730/WCAS/ENVR_SCI/390-0/28232.html) Northwestern University
- [PD-15 - R for Geospatial Analysis and Mapping](https://gistbok.ucgis.org/bok-topics/r-geospatial-analysis-and-mapping), University Consortium for Geographic Information Science
<!-- [GEO503: Spatial Data Science](http://adamwilson.us/SpatialDataScience/) -->
- [CRD 298: Spatial Methods in Community Research](https://crd230.github.io/index.html),  Professor [Noli Brazil](https://humanecology.ucdavis.edu/people/noli-brazil), University of California, Davis 
- [CP6521 Advanced GIS](https://rstudio-pubs-static.s3.amazonaws.com/460816_f7e4d237e0334e9887323686041bd762.html), [Yongsun Lee](https://sites.google.com/view/yongsunglee), Georgia Tech
- [Urban Data Analytics in R](https://sia.planning.unc.edu/teaching/techniques-course/), [Nikhil Kaza](https://sia.planning.unc.edu/), University of North Carolina at Chapel Hill
-  [Geospatial Analytics](https://le.ac.uk/modules/2019/gy7707), taught by Dr [Nick Tate](https://www2.le.ac.uk/departments/geography/people/njt9) as part of the MSc in Geographical Information Science at the Unversity of Leicester, UK.
-  [GEOG 28402 & 28403: Geographic Information Science II & III](https://geography.uchicago.edu/content/geographical-sciences-and-gis-courses), [Marynia Kolak](https://makosak.github.io/) at the [Center for Spatial Data Science](https://makosak.github.io/), Unversity of Chicago

### Other teaching courses/lectures/guides using the book

- [Data Science for Economists, EC 607](https://github.com/uo-ec607/lectures)
- [11th International Summer School2019: Spatial and digital Epidemiology: Leveraging geo-referenced social media in the context of urban health](http://spatialepidemiology.strikingly.com/)
- [Data Carpentry: Introduction to Geospatial Raster and Vector Data with R](https://datacarpentry.org/r-raster-vector-geospatial/)
- [R: Mapping and Geospatial](https://guides.library.duke.edu/r-geospatial) guide, Duke University

### Book reviews

> I first read the first edition around 3 years ago and was astounded that everything I had been doing piecemeal in Q, Arc, and with some sf functions could be done in an orderly manner and finally the geospatial libraries were accessibly explained. Sadly at the time I did not get past the first part and thought "this is great! but need to move on!". A month or so ago I sat down to reread the book in its entirety, with the move to terra etc.

>  Beautiful book: A must-read if you're into data analytics/science with R and do geospatial analysis.

See the rest of these reviews and maybe add your own review [here](https://www.amazon.com/Geocomputation-Chapman-Hall-Robin-Lovelace/dp/1138304514/). 

### Social media

{{< tweet dgkeyes 1212123222931456000 >}}
{{< tweet dikayodata 1519067757811228672 >}}
{{< tweet BriChronister 1471963795908009986 >}}
{{< tweet AuliaRBachtiar 1435036079485112321 >}}
{{< tweet dr_bala_s 1314211766893645824 >}}
{{< tweet kyle_e_walker 1252604577037385728 >}}
{{< tweet virtualnaman 1222392518177783811 >}}
{{< tweet jcusens 1202893592009805825 >}}
{{< tweet MaryniaKolak 1103527764035096576 >}}
{{< tweet geoviews 1084753004178358272 >}}
{{< tweet KitMacleod 1074561874195292162 >}}
{{< tweet cdhowe 1073280734926909442 >}}
{{< tweet PONiittynen 1073112001382105088 >}}
{{< tweet Thienthanh_le 1046710705267695616 >}}
{{< tweet harpactes 1046560803745406977 >}}
{{< tweet mbrcalles 1032678122859032576 >}}
