---
title: 
author: Jakub Nowosad
date: '2021-01-25'
slug: whyr_webinar004
categories: [vignette]
tags: [tmap]
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE,
                      fig.width = 6, 
                      fig.height = 4)
```

<!-- intro -->
<!-- arranging maps/plots -->
<!-- tmap has been great for maps -->
<!-- additionally, arrange help in simple cases -->
<!-- however, there was a limitaion for more complex cases -->
<!-- link to previous examples -->
<!-- tmap 3.3 introduces tmap_grob -->
<!-- this opens many possibilities -->
<!-- this This vignette shows... -->

#

```{r}
library(tmap)
data(World)

tm1 = tm_shape(World) + tm_polygons("well_being", 
                                    title = "Well-being",
                                    palette = "RdYlGn")
tm2 = tm_shape(World) + tm_polygons("inequality", 
                                    title = "Inequality",
                                    palette = "-RdYlGn")
```

```{r}
tmap_arrange(tm1, tm2, ncol = 2)
```

# grobs

```{r}
tm1_grob = tmap_grob(tm1)
```

```{r}
tm2_grob = tmap_grob(tm2)
```


# 

```{r}
library(gridExtra)
```

```{r}
grid.arrange(tm1_grob, tm2_grob, 
             top = "Two separate maps", ncol = 2)
```



# 

```{r}
library(cowplot)
pg1 = plot_grid(tm1_grob, tm2_grob, 
          labels = c("A", "B"),
          nrow = 1)
pg1
```


# 

```{r}
library(ggplot2)
gg1 = ggplot(World, aes(well_being, inequality)) +
  geom_point() +
  labs(x = "Well-being", y = "Inequality")

plot_grid(pg1, gg1, 
          labels = c("A", "B"),
          nrow = 1) 
```

# Inset maps

```{r}
tm3 = tm_shape(World) + 
  tm_polygons("well_being", 
                                    title = "Well-being",
                                    palette = "RdYlGn", lwd = 0.2) +
  tm_layout(legend.show = FALSE)
tm4 = tm_shape(World, bbox = "Europe") + 
  tm_polygons("well_being", 
                                    title = "Well-being",
                                    palette = "RdYlGn") 

tm3_grob = tmap_grob(tm3)
tm4_grob = tmap_grob(tm4)

pg2 = ggdraw() +
  draw_plot(tm4_grob) +
  draw_plot(tm3_grob,
            width = 0.2, height = 0.2,
            x = 0.25, y = 0.75)
pg2
```

