---
title: "What's is new in the second edition of Geocomputation with R: part 1"
author: Jakub Nowosad, Robin Lovelace, Jannes Muenchow
date: "2022-01-30"
slug: geocompr2-bp2
categories: [updates]
tags: [geocompr, geocompr2, sf, sp, stars, raster, terra, tmap, rstats]
draft: true
---

<!-- intro -->
Geocomputation with R is a book on geographic data analysis, visualization, and modeling.
Its first edition was published in 2019 and reached about 500k people via the website at https://geocompr.robinlovelace.net/ and [the physical book](https://www.routledge.com/9781138304512). 
The book also contributes to many university courses, lectures, and personal development as outlined at https://geocompr.github.io/guestbook/.
Tools and methods for spatial data analysis are still quickly evolving, and thus we decided in September 2021 to start working on the second edition of the book.
At the time of writing this blog post, we made a lot of alterations to the first part of the book called *Foundations*, and the main role of this document is to list and explain the changes.
The second edition (work in progress) is available at https://geocompr.robinlovelace.net/, while you can find the first edition at https://bookdown.org/robinlovelace/geocompr/.

## Major changes

- Replacement of `raster` with `terra` in Chapters 1 to 7 (see commits related to this update [here](https://github.com/Robinlovelace/geocompr/search?q=terra&type=commits)) 
- major improvements to Reprojecting geographic data
- Improved the Coordinate Reference Systems section - both prose and figures
- I would suggest using the authority:code style of specifying CRSs through the book.


## Changes to specific chapters

<!-- ch1 -->
- Updated history

<!-- ch2 -->
- s2 mentioned in ch2
- Adds section R packages for working with raster data

<!-- ch4 -->
- Improved communication of binary spatial predicates in Chapter 4 (see [#675](https://github.com/Robinlovelace/geocompr/pull/675))
- New [section](https://geocompr.robinlovelace.net/spatial-operations.html#de-9im-strings) on the dimensionally extended 9 intersection model (DE-9IM)

<!-- ch5 -->
- New section on the links between subsetting and clipping (see [#698](https://github.com/Robinlovelace/geocompr/pull/698)) in Chapter 5
- terra resampling much improved

<!-- ch6 -->
- New [chapter](https://geocompr.robinlovelace.net/raster-vector.html) on raster-vector interactions split out from Chapter 5

<!-- ch8 -->
- many improvements to I/O - more data packages, geocoding part, GeoTIFF COG, read_sf <- st_read; write_sf <- st_write, ogr sql, COG reading
- Update of Chapter 8 to include mention alternative ways or reading-in OSM data in [#656](https://github.com/Robinlovelace/geocompr/pull/656)


## Book infrastructure

- Saved some R spatial objects to files in both spData and spDataLarge - this way, we can read data using raster/terra/stars, instead of just loading one package's class object into R memory
- Created external website for solutions
- Refactor build settings so the book builds on Docker images in the [geocompr/docker](https://github.com/geocompr/docker) repo
- Improve the experience of using the book in Binder (ideal for trying out the code before installing or updating the necessary R packages), as documented in issue [#691](https://github.com/Robinlovelace/geocompr/issues/691) (thanks to [yuvipanda](https://github.com/yuvipanda))


## Minor changes

- Recreated several plots using the tmap package
- Customize the look of text blocks
- Many small changes...


<!-- outro -->
- info about "This means that anyone still using these packages should "**transition to sf/stars/terra functions using GDAL and PROJ at your earliest convenience**"."
- issues/suggestions/PRs
- thanks to some people?
- ask people for their opinions?
